services:
  react:
    container_name: ocean_gym_react-production
    image: ocean_gym_react:prod
    build:
      context: ./Ocean_gym_react
      target: production
      args:
        - NODE_ENV=production
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"

  ocean_gym_django:  
    image: ocean_gym_django 
    container_name: ocean_gym_django
    build:
      context: ./OCean_gym_django
    ports:
      - "8000:8000"
    volumes:
      - ./OCean_gym_django:/app
    command: ["./wait-for-it.sh", "-t", "30", "mysql:3306", "--", "gunicorn", "--bind", "0.0.0.0:8000", "myproject.wsgi:application"]
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Ocean_Gym
    volumes:
      - django_react_data:/data/db
      - ./dumps:/docker-entrypoint-initdb.d:ro

volumes:
  django_react_data:
