# Generated by Django 5.1.1 on 2024-09-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_client_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
