# Generated by Django 5.1.1 on 2024-10-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_client_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
