# Generated by Django 5.1.1 on 2024-09-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_client_fecha_creacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='clientes',
        ),
    ]
