# Generated by Django 5.1.1 on 2024-09-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_client_clientes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clientes',
            new_name='Client',
        ),
    ]
