# Generated by Django 5.1.1 on 2024-10-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_id_cliente_inscripcion_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
