# Generated by Django 5.1.1 on 2024-09-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_administrador_client_apellido_client_telefono_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='id',
            new_name='id_cliente',
        ),
    ]
