# Generated by Django 5.1.1 on 2024-10-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_inscripcion_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
