# Generated by Django 5.1.1 on 2024-10-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_inscripcion_fecha_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='gmail',
            field=models.CharField(max_length=200),
        ),
    ]
