# Generated by Django 5.1.1 on 2024-10-23 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_inscripcion_gmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDePagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('gmail', models.EmailField(max_length=200)),
                ('monto', models.FloatField()),
                ('id_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inscripcion')),
            ],
        ),
    ]
