# Generated by Django 5.1.1 on 2024-10-24 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_registrodepagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodepagos',
            name='id_inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.inscripcion'),
        ),
    ]
