# Generated by Django 5.1.1 on 2024-10-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_metododepago_venta_id_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id_metodo_pago',
        ),
    ]
