# Generated by Django 5.1.1 on 2024-09-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_metododepago_venta_id_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='id_administrador',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_metodo_pago',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Inscripcion',
        ),
        migrations.DeleteModel(
            name='MetodoDePago',
        ),
    ]
