# Generated by Django 5.1.1 on 2024-10-25 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_registrodepagos_id_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
