# Generated by Django 5.1.1 on 2024-10-04 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_inscripcion_id_administrador_and_more'),
        ('api', '0013_remove_venta_id_metodo_pago'),
    ]

    operations = [
    ]
