# Generated by Django 5.1.1 on 2024-10-31 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_client_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='gmail',
            new_name='email',
        ),
    ]
