# Generated by Django 5.1.1 on 2024-10-31 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_gmail_inscripcion_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrodepagos',
            old_name='gmail',
            new_name='email',
        ),
    ]
